# Generated by Django 6.0.1 on 2026-02-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='Дата и время платежа', verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Введите сумму оплаты', max_digits=10, verbose_name='Сумма оплаты')),
                ('payment_option', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], help_text='Выберите способ оплаты', max_length=20, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, help_text='Выберите оплаченный курс', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.course', verbose_name='Оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, help_text='Выберите оплаченный урок', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='courses.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('paid_course__isnull', False), ('paid_lesson__isnull', True)), models.Q(('paid_course__isnull', True), ('paid_lesson__isnull', False)), _connector='OR'), name='only_course_or_lesson')],
            },
        ),
    ]
