name: Django CI

on: [push, pull_request]

jobs:
  # запуск линтеров
  lint:
    runs-on: ubuntu-latest
    steps:
      # получаем код из репозитория
      - name: Check out code
        uses: actions/checkout@v3
      # устанавливаем python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      # устанавливаем Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      # устанавливаем зависимости
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      # устанавливаем flake8
      - name: Run flake8
        run: poetry run flake8 .
  # запуск тестов
  test:
    # только после успешного запуска линтеров
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: poetry run python manage.py test
  # сборка докер-образа
  build:
    # только после успешных тестов
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # авторизация в docker hub через секреты
      - name: Log in in Docker hub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      # собираем докер-образ на основе последнего коммита
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/mindshare-api:${{ github.sha }} .
      # отправка собранного образа в docker hub
      - name: Push Docker image in Docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mindshare-api:${{ github.sha }}

  deploy:
    # только после успешной сборки docker-образа
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh private key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mindshare-api:${{ github.sha }}                                         
          docker stop mindshare-api || true
          docker rm mindshare-api || true
          docker run -d --name mindshare-api \
            -p 80:8000 \
            -e USE_SQLITE=True \
            -e SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" \
            -e DEBUG=False \
            ${{ secrets.DOCKER_HUB_USERNAME }}/mindshare-api:${{ github.sha }}
          EOF
